application: omniboomer-videoconference
version: 4
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /html
  static_dir: html

- url: /images
  static_dir: images 

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: server.app
  secure: always
  
inbound_services:
- channel_presence
- warmup
